todo_list_project/todo_list/urls.py
from django.urls import path
from . import views


app_name = "todo_list" 
urlpatterns = [ 
    path('', views.overview, name="overview"),
    path('<int:todo_id>/', views.detail, name="detail"),
    path('<int:todo_id>/status_change', views.status_change, name="status_change"),
    path('new', views.new, name="new"),
]

todo_list_project/todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('todo_list/', include("todo_list.urls"))
]

todo_list_project/todo_list/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"



class Todo(models.Model):
    status_choices = [
        ("D", "Done"),
        ("T", "Todo"),
        ("C", "Canceled")
    ]

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    deadline = models.DateTimeField()
    status = models.CharField(max_length=1, choices=status_choices, default="T")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} {self.category} {self.status} {self.deadline}"

todo_list_project/todo_list/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect
from .models import Todo, Category

# Create your views here.
def overview(request):
    todos = Todo.objects.all()
    return render(request, 'todo_list/overview.html', {"todos": todos, "status_choices": Todo.status_choices, "categories": Category.objects.all()})

def detail(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    return render(request, 'todo_list/detail.html', {'todo': todo})

def status_change(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.status = request.POST["status"] # selber name wie im <select>-tag
    todo.save()
    return HttpResponseRedirect(reverse('todo_list:overview'))

def new(request):
    name = request.POST["name"]
    description = request.POST["description"]
    status = request.POST["status"]
    deadline = request.POST["deadline"]
    category = Category.objects.get(pk=request.POST["category"])

    print(name, description, status, deadline, category)

    Todo.objects.create(name=name,
                        description=description,
                        status=status,
                        deadline=deadline,
                        category=category)
    return HttpResponseRedirect(reverse('todo_list:overview'))

todo_list_project/todo_list/templates/todo_list/detail.html
<table>
    <tr><th>Feld</th><th>Value</th></tr>
    <tr><td>Name</td><td>{{todo.name}}</td></tr>
    <tr><td>Status</td><td>{{todo.status}}</td></tr>
    <tr><td>Deadline</td><td>{{todo.deadline}}</td></tr>
    <tr><td>Description</td><td>{{todo.description}}</td></tr>
    <tr><td>Kategorie</td><td>{{todo.category}}</td></tr>
    </tr>
  </table>

todo_list_project/todo_list/templates/todo_list/overview.html
<h1>Todo-List</h1>
<table>
  <tr><th>Name</th><th>Status</th><th>Deadline</th><th>Action</th></tr>
  {% for todo in todos %}
  <tr>
    <td><a href="{% url 'todo_list:detail' todo.id %}">{{todo.name}}</a></td>
    <td>{{todo.status}}</td>
    <td>{{todo.deadline}}</td>
    <td>
      <form action="{% url 'todo_list:status_change' todo.id %}" method="post">
        {% csrf_token %}
        <select name="status">
          {% for item in todo.status_choices %}
          <option value="{{item.0}}">{{item.1}}</option>
          {% endfor %}
          </select>
        <input type="submit" value="Change">
      </form>
    </td>
  </tr>
  {% endfor %}
</table>

<form action="{% url 'todo_list:new' %}" method="post">
  {% csrf_token %}
  <label>Name</label><input type="text" name="name"><br>

  <label>Beschreibung</label><input type="text" name="description"><br>

  <label>Status</label>
  <select name="status">
    {% for item in status_choices %}
      <option value="{{item.0}}">{{item.1}}</option>
    {% endfor %}
  </select><br>

  <label>Kategorie</label>
  <select name="category">
    {% for item in categories %}
    <option value="{{item.id}}">{{item}}</option>
    {% endfor %}
  </select><br>

  <label>Deadline</label>
  <input type="date" name="deadline">
  <input type="submit" value="Anlegen">
</form>